### ISSUE TITLE
Configure build to download dependencies

### ISSUE THREAD

**Issue by durera** [ibm-iotf/connector-messagehub#1]
Can we do this http://www.thejavageek.com/2015/06/02/download-dependencies-using-gradle/ so that the dependencies are pulled in when we build (and have them included in .gitignore) rather than having the libraries in the repo itself, or is there some reason that's not an option?

**Comment by leo-davison** [comment]
Updated grade build to retrieve the dependencies from maven.  The message-hub login module is not available on maven, so this is still bundled in this repo at this stage.
